version: "3.9"
services:
  db:
    container_name: db
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=pguser
      - POSTGRES_USER=pguser
    # NOTE: Port forwarded for local development
    ports:
      - "5432:5432"
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
      #-./data/production/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  app:
    build: .
    command: bash -c "chmod +x /usr/bin/entrypoint.sh && /usr/bin/entrypoint.sh"
    environment:
      SECRET_KEY_BASE: 8718e1e82dd879de243d6031cd40f75305e475b091875c78cbdfc01a786cb4e3295e171e81d71a16ce0e31a3b5d5406ff85c84a483e8ccc5ca9b23af34f4326d
      DATABASE_URL: postgresql://pguser:pguser@db:5432/postgres
      APP_DB_USER: pguser
      APP_DB_PASSWORD: pguser
      POSTGRES_HOST: db
      DOCKER_ENV: 1
      NODE_VERSION: 14.x
    volumes:
      - .:/myapp
    ports:
      - "80:3000"
    depends_on:
      - db
volumes:
  postgres_data:
    driver: local
